version: '3'

services:
  node-example:
    container_name: node-example
    build: .
    command: ["npm", "run", "start-dev"]
    ports:
      - "9876:9876"
    volumes:
      - ${PWD}:/var/www:delegated
    environment:
      - APP_FOO=bar
