version: '3'

services:
  localenv-example-node:
    container_name: localenv-example-node
    build: .
    command: ["npm", "run", "start-dev"]
    ports:
      - "8081:8081"
    volumes:
      - ${PWD}:/var/www:delegated
    networks:
      - localenv_network

networks:
  localenv_network:
    external: true
